#!/bin/bash
SHA1=$(echo -n "$1" | openssl dgst -sha1 | awk '{print $2}' | tr '[:lower:]' '[:upper:]')
SHASHORT=$(echo -n "$SHA1" | perl -pe 's@([0-9a-zA-Z]{5}).+@\1@')
SHASEARCH=$(echo -n "$SHA1" | perl -pe 's@[0-9a-zA-Z]{5}(.+)@\1@')
URL="https://api.pwnedpasswords.com/range/$SHASHORT"
echo ""
RES=$(curl --silent $URL)
RES=$(echo "$RES" | grep "$SHASEARCH" | wc -l)
if [ "$RES" == "0" ] ; then
	ansiprintf '%f2>%s%rst>' 'Password is safe!'
else
	ansiprintf '%f1>%s%rst>' 'Password is compromised!'
fi
echo ""
echo ""
